version: '2.4'

services:
    db:
        image: arminc/clair-db:latest
        #image: postgres:10.4-alpine
        restart: on-failure
        healthcheck:
            test: nc -z db 5432
            interval: 1s
            retries: 20
    clair:
        image: arminc/clair-local-scan:v2.0.3
        links:
        - db:postgres
        depends_on:
            db:
                condition: service_healthy
        restart: on-failure
        healthcheck:
            test: nc -z clair 6060 && nc -z clair 6061
            interval: 1s
            retries: 20
    scanner:
        image: clair-container-scan:tmp1
        links:
        - clair
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        depends_on:
            clair:
                condition: service_healthy
